### ISSUE TITLE
Tratamento após a exclusão de um formulário com status aprovado

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#105]
## Descrição:
Quando o administrador realiza a ação de Aprovar ou Negar algum formulário a página é recarregada, trazendo o mapa atualizado para a interface. Porém quando a ação de excluir ocorre o mapa não é atualizado, contendo um marcador que não corresponde a nenhum local/serviço cadastrado. 

## Tarefas:
- [x] Implementar alguma ação que recarregue o mapa atualizado após a exclusão de um formulário com status aprovado 

## Testes:
- [x] Mapa atualizado após a exclusão de algum formulário com status aprovado
- [x] Correto funcionamento da funcionalidade de exclusão

**Comment by MarcosViniciusG** [comment]
Agora a página recarrega após a exclusão de um formulário qualquer.
