### ISSUE TITLE
Atualização nas ações da interface do administrador

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#111]
## Descrição:
Na interface do administrador as ações ainda não estão disponibilizadas de forma coerente, é necessário atualizar o agrupamento de ações do admin.

## Tarefas:
- [x] Adicionar o botão de edição (Ainda em não funcionamento)
- [x] Agrupar os botões de ação (Aprovar, Negar,  Editar e Excluir) na mesma coluna da tabela
- [x] Alterar a ação de excluir para ser um botão (idêntico aos outros)

## Testes:
- [x] Botões de ação agrupados nas tabelas da interface
- [x] Padronização no desing  dos botões
- [x] Correto funcionamento dos botões de Aprovar, Negar e Excluir (Edição ainda em não funcionamento)

**Comment by Max-Rohrer20** [comment]
A adição da função do botão de Excluir foi adicionada pelo @MarcosViniciusG na Issue #105.
Abaixo segue um print com a nova disposição dos botões.
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/452ad431-af41-4284-a0ed-d71fe188b550)
