### ISSUE TITLE
Desenvolvimento do wireframe da interface do administrador

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#115]
## Descrição:
O wireframe anteriormente criado contém uma ideia inicial da interface, se mostra necessário a adição de algumas funcionalidades e um novo visual para as tabelas.

## Tarefas:
- [x] Adição de funcionalidades desenvolvidas no projeto 
- [x] Novo design para as tabelas

## Testes:
- [x] Disponibilização correta do wireframe na documentação (Gitpages)

**Comment by guslnhm** [comment]
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/143884487/10596d17-442b-4815-82cd-dfd8d87f6cbe)



![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/143884487/a8656f5a-57a4-4269-a98b-89be9d4e2e47)
