### ISSUE TITLE
Envio de emails após a submissão de algum formulário

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#116]
## Descrição:
O desenvolvimento do envio de emails após um formulário ser submetido, visando o auxilio para a administração dos formulários.

## Tarefas:
- [x] Após um formulário ser submetido uma notificação ser enviada para o email do administrador
- [x] Mensagem do email ser informativa e contendo dados não sensíveis

## Testes:
- [x] Correto envio dos emails para o email do administrador

**Comment by Max-Rohrer20** [comment]
O e-mail está sendo enviado para o e-mail cadastrado diretamente no WordPress. A mensagem contém o nome do loca cadastrado, tipo de serviço, data e hora que o cadastro foi feito e o link para acessar o painel de adminstração diretamente.

![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/c63c2493-e6d0-4eee-93cd-3583dfd2891d)
