### ISSUE TITLE
Criação dos filtros de tabelas na interface

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#119]
## Descrição:
Para a fidelização com o wireframe da interface desenvolvido, mostra-se necessário o desenvolvimento de filtro das tabelas, visando a disponibilização de ferramentas que auxiliem o administrador.

## Tarefas:
- [x] Criação de seleção de tabelas a ser mostrada na interface (Quando clicado a tabela irá ser a única na tela)
- [x] Criação de um contador de quantos formulários contém cada status (Aprovado, Negado e pendente) 
- [x] O contador estar presente nos filtros

**Comment by MarcosViniciusG** [comment]
Adicionado filtros por status do formulário (funcional e com contador) e filtros por nome e serviço (não funcionais).
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/85762681/30d3008e-c323-4819-8c14-4ecd99de6c92)
