### ISSUE TITLE
Adição de filtros na interface por nome do formulário

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#127]
## Descrição:
Na interface do administrador mostra-se necessário a criação de um filtro por nome para maior eficiência na hora do administrador revisar os formulários.

## Tarefas:
- [x] Adição de filtro que mostra apenas linhas que tenham no nome as letras pesquisadas
- [x] Adição de um contador com o número de resultados

## Testes:
- [x] Após cada tecla pressionada, o filtro atualiza
- [x]  O contador mostra o número correto de formulários que correspondem ao resultado

**Comment by MarcosViniciusG** [comment]
Filtro e contador adicionados.
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/85762681/1b4ee687-0e89-4efb-a681-f0e4b92ec179)
