### ISSUE TITLE
Desenvolvimento do desing da interface

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#163]
## Descrição:
Se mostra necessário o desenvolvimento visual da interface do administrador para melhor interação com o usuário.

## Tarefas:
- [x] Atualizar o desing das tabelas
- [x] Atualizar o desing dos filtros
- [x] Atualizar o desing dos botões ações

**Comment by Punkrig** [comment]
![Captura de tela de 2024-07-04 10-05-51](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/111445872/d3822f20-a0d8-42e1-a336-150916e58f75)
![Captura de tela de 2024-07-04 10-06-22](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/111445872/d87b3d31-b74e-4c70-8ff1-159cc630b074)
