### ISSUE TITLE
Desenvolvimento do design da tela de edição

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#164]
## Descrição:
Visto o desenvolvimento da tela de edição, mostra-se necessário a atualização do visual da tela, buscando trazer melhor interação com a ferramenta. Além da criação do wireframe no figma para documentação da tela de edição.

## Tarefas:
- [x] Desenvolvimento do design dos campos de edição
- [x] Organização dos campos na tela
- [x] Desenvolvimento do visual dos botões
- [x] Adição do botão de fechar (X) e cancelar
- [x] Disponibilização do wireframe (Figma) na documentação

**Comment by MarcosViniciusG** [comment]
O wireframe foi criado na plataforma do Figma. Link para visualizar: https://www.figma.com/proto/lNCaAThBRSfTr5KWtONYVs/Wireframe-da-tela-de-edi%C3%A7%C3%A3o-de-formul%C3%A1rio?node-id=5-2&t=iSIwekgosvbfu0c3-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A2
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/85762681/dcc18a7b-64b5-401a-a8ee-98fac80744c4)
