### ISSUE TITLE
Marcador personalizado

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#166]
## Descrição:
Nos mapas utilizados no plugin o marcador pode receber a identidade visual da comunidade LGBTQ+.

## Tarefas:
- [x] Marcadores dos mapas possuírem identidade com o plugin (Comunidade LGBTQ+)

## Testes:
- [x] Correto funcionamento dos marcadores

**Comment by Max-Rohrer20** [comment]
A adição do marcador personalizado foi feita com sucesso na página do formulário e na página de administração no painel do wordpress.

Marcador na página inicial do formulário:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/c0a3dd62-5e50-49a3-be59-e67f6da03612)

Pop-up do marcadoe na páfina inicial do formulário:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/bc4fdc17-2db1-4223-9cf7-82249663db88)

Marcador ao fazer a resposta do formulário:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/db71cc16-8a9f-4e40-a54d-1ada1431fb2c)

Marcador na página após o envio do formulário:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/bb01a177-ad94-430a-ac75-3e698d1e1af7)
m/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/596eab4a-cf20-443a-978e-66937f32a81d)


Marcador na página de administração no painel do Wordpress:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/831e55d6-8335-46be-9047-e58d3da21d79)
