### ISSUE TITLE
Criação dos marcadores personalizados

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#186]
## Descrição:
De acordo com o tipo de serviço selecionado o marcador mostrado no mapa deverá ser personalizado para cada serviço respectivo. No caso do tipo de serviço personalizado (Outro), o marcador deve seguir o padrão (default).

## Tarefas:
- [x] Criação dos marcadores personalizados para cada tipo de serviço

## Testes:
- [x] Disponibilização dos arquivos na documentação

**Comment by Max-Rohrer20** [comment]
Os modelos dos marcadores personalizados ficaram no seguinte modelo que estão abaixo, eles podem ser alterados futuramente.

Marcador Padrão:
![Image](https://github.com/user-attachments/assets/896f76d7-6fa7-4639-9df0-10497a5f411d)

Marcador Academia:
![Image](https://github.com/user-attachments/assets/218b21e8-ea84-423f-af37-b9d270ebba97)

Marcador Bares/Restaurante
![Image](https://github.com/user-attachments/assets/9d857677-76d9-42fd-8580-718be62f36f1)

Marcador Beleza:
![Image](https://github.com/user-attachments/assets/e775ec57-d272-4113-b3a1-d3da37b8a651)

Marcador Ensino:
![Image](https://github.com/user-attachments/assets/25447ed0-8218-47d5-8f43-d6302c1793b2)

Marcador Entretenimento:
![Image](https://github.com/user-attachments/assets/91dd6980-cf43-4702-994f-55da177a95bf)

Marcador Hospedagem:
![Image](https://github.com/user-attachments/assets/75b0c853-69cf-4e6c-af24-573e413a585f)

**Comment by Max-Rohrer20** [comment]
Os modelos dos marcadores personalizados ficaram no seguinte modelo que estão abaixo, eles podem ser alterados futuramente.

Marcador Padrão:
![Image](https://github.com/user-attachments/assets/896f76d7-6fa7-4639-9df0-10497a5f411d)

Marcador Academia:
![Image](https://github.com/user-attachments/assets/218b21e8-ea84-423f-af37-b9d270ebba97)

Marcador Bares/Restaurante
![Image](https://github.com/user-attachments/assets/9d857677-76d9-42fd-8580-718be62f36f1)

Marcador Beleza:
![Image](https://github.com/user-attachments/assets/e775ec57-d272-4113-b3a1-d3da37b8a651)

Marcador Ensino:
![Image](https://github.com/user-attachments/assets/25447ed0-8218-47d5-8f43-d6302c1793b2)

Marcador Entretenimento:
![Image](https://github.com/user-attachments/assets/91dd6980-cf43-4702-994f-55da177a95bf)

Marcador Hospedagem:
![Image](https://github.com/user-attachments/assets/75b0c853-69cf-4e6c-af24-573e413a585f)
