### ISSUE TITLE
Alerta visual nos campos inválidos

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#188]
## Descrição:
Quando algum campo de preenchimento (no envio de formulários e edição dos formulários) estiverem com campos inválidos é necessário um aviso nos campos que foram preenchidos de forma correta ou não.

Exemplo:

![validacao](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/124713089/911937fe-9cef-4f4c-af76-a311e741d65e)

## Tarefas:
- [ ] No processo de validação na tentativa de envio (formularios e tela de edição) existir um retorno visual sobre qual campo esta incorreto

## Testes:
- [ ] Correto barramento de campos com entradas maliciosas
- [ ] Correto funcionamento das mensagens de erro em diferentes telas

**Comment by MarcosViniciusG** [comment]
Foram implementados os alertas visuais em cada campo.
Tudo negado:
![image](https://github.com/user-attachments/assets/df14cf39-8e9a-43d4-8960-2f3a0db975d4)

Tudo aprovado:
![image](https://github.com/user-attachments/assets/7f8d87f9-4702-4ecc-8e39-eb6d225e5e7d)
