### ISSUE TITLE
Resolver bug no envio do formulário

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#19]
# Etapas para validação:

- [x] Não aparecer a opção de reenviar o formulário quando tentar atualizar a página.

## Resumo sobre:

Quando enviado um formulário e atualizado a página aparece uma opção do navegador para reenviar o formulário, caso confirmado é duplicado o último formulário enviado.

**Comment by Max-Rohrer20** [comment]
Erro corrigido com a adição do comando:
 wp_redirect($_SERVER['REQUEST_URI']);                   
exit;
