### ISSUE TITLE
Melhoria do bloco de ações da tabela do administrador

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#193]
## Descrição:
O bloco de ações do administrador ainda se mostra visualmente não intuitivo para o usuário (administrador). Mostra-se necessário o desenvolvimento do desing (mudança de cores, disponibilização dos botões e o bloco em si).

## Tarefas:
- [ ]  Desenvolvimento do desing do bloco de ações da tabela

## Testes:
- [ ] Correto funcionamento das funcionalidades de ações

**Comment by Punkrig** [comment]
![Captura de tela de 2024-08-11 21-46-16](https://github.com/user-attachments/assets/2dda3e1a-f32e-4022-8256-e06414a4038c)
