### ISSUE TITLE
Criação da tela download da landing page

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#199]
## Descrição:
Desenvolvimento da tela de download da landing page do plugin, onde o usuário poderá realizar o download e ter acesso ao tutorial de instalação no wordpress.

## Tarefas:
- [x] Desenvolvimento da página download da landing page
- [x] Contendo botão onde ocorra o download do arquivo zip do plugin
- [x] Conter tutorial de instalação do plugin no wordpress
- [x] Respeitar a responsividade em dispositivos mobile 

## Testes:
- [x] Correto funcionamento das funcionalidades do site

**Comment by Punkrig** [comment]
![Uploading Captura de tela de 2024-08-11 21-51-03.png…]()
