### ISSUE TITLE
Mudança nos marcadores (pins) personalizados

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#202]
## Descrição:
Para melhor visualização dos marcadores no mapa mostra-se necessário a alteração do desing, tendo em vista o contraste dos marcadores em relação ao mapa.

Sugestão: Cada tipo de serviço ser correspondente a uma cor da bandeira LGBTQ+. E um marcador genérico contendo toda a bandeira.

## Tarefas:
- [x]  Desenvolvimento de novos marcadores personalizados para melhor exibição no mapa

## Testes:
- [x] Disponibilização dos marcadores na documentação

**Comment by Max-Rohrer20** [comment]
Agora temos 6 novos tipo de marcadores, que estão definidos de acordo com a cor que foi definida para o filtro de serviço e 1 marcador padrão para os tipos de serviços por fora dos 6 definifidos:


Marcador Bares e Restaurantes:
![Image](https://github.com/user-attachments/assets/69690f53-37c8-426d-b177-218fbc4a3087)

Marcador Beleza:
![Image](https://github.com/user-attachments/assets/2fa5db1d-d2de-4dcc-9086-13ae41c9d177)

Marcador Entretenimento
![Image](https://github.com/user-attachments/assets/4fbe07ce-0096-4401-83a8-e8d0479de5a7)

Marcador  Hospedagem: 
![Image](https://github.com/user-attachments/assets/f0a000a8-3d6d-44eb-ad91-7a7030d26279)

Marcador Ensino:
![Image](https://github.com/user-attachments/assets/cea9effb-dbdc-4fdc-b723-fa0c1e8aa92a)

Marcador Academia:
![Image](https://github.com/user-attachments/assets/78287a49-c30e-4e50-a4e3-02e8c40f976d)

Marcador Outros:

![Image](https://github.com/user-attachments/assets/f981bf90-f10b-4f64-a507-0fa2f00dd7c2)
