### ISSUE TITLE
Adicionando tela inicial do wireframe

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#31]
# Etapas para validação:

- [ ] O mapa com as marcações na tela incial
- [ ] Botão para ter acesso ao formulário

## Resumo sobre:

Na tela inicial do wireframe ser o mapa com algumas marcações.

**Comment by guslnhm** [comment]
Ideia de funcionalidades/conteúdos da tela inicial:
1. Breve explicação de como funciona (indicando a procurar o estabelecimento no mapa, explicando a dinâmica de preencher o formulário e o processo de validação);
2. Mapa com estabelecimentos já mapeados como LGBTQ+ friendly
3. Opção de busca por:
   - Tipo de serviço
   - Nome
   - Localidade:
     - Estado
     - Cidade
 5. Botão de preencher formulário
 
Quando seleciona um estabelecimento já mapeado como LGTBQ+ friendly, o que deve ser exibido?
	- Nome do estabelecimento
	- Informações inseridas no cadastro?
		- E-mail
		- Tipo de serviço
		- Público-alvo específico
		- Descrição
	- Contato? Celular/WhatsApp?
