### ISSUE TITLE
Editar o readme da página inicial

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#5]
# Etapas para validação:

- [x] conter nome e descrição do projeto
- [x] o que o nosso plugin faz
- [x] membros da equipe

## Resumo sobre:

Editar o readme do projeto para conter informações importantes sobre o projeto.

**Comment by Max-Rohrer20** [comment]
Redame alterado e commit feito
