### ISSUE TITLE
Nova organização dos formulários na interface

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#68]
## Descrição:
Na interface do admin se mostra necessário separar os formulários de acordo com o status para que fique de forma mais organizada e legível

## Tarefas:
- [x] Os formulários registrados no BD serem mostrados em 3 tabelas de acordo com os 3 tipos de status (Aprovado, rejeitado e pendente)

## Testes:
- [x] Interface contendo as 3 tabelas
- [x] Quando alterado o status de um formulário o mesmo ser movido para sua nova tabela
- [x] Correto funcionamento das funcionalidade de aprovar, rejeitar e excluir

**Comment by Max-Rohrer20** [comment]
Adicionei a função de aprovar e negar as respostas dos formulário. Abaixo tem alguns prints que mostram o funcionamento dele no meu local host

Resposta de Formulário recém adicionada:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/1bd533e0-4aee-434b-bc8f-dd01794f1494)
Resposta aprovada:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/ea8395ef-2028-40da-952b-d8f246ab7afa)
Resposta Negada após ser aprovada:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/59356197-b7ff-45ba-8ba6-0a551f21d2a3)
Resposta Excluida:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/be2ed09b-262f-445b-962b-63e954a8b36a)
