### ISSUE TITLE
Ajuste na tela de confirmação de envio do formulário

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#69]
## Descrição:
Na tela de confirmação de envio do formulário contém um erro de redirecionamento no botão (Cadastrar um novo local) que volta para a tela inicial e não a tela de formulário. Além da falta de um botão para voltar para tela inicial de forma similar a tela do formulário (Voltar).

 
## Tarefas:
- [x] Adicionar um botão para voltar para a página inicial na tela de confirmação de envio do formulário
- [x] Ajustar o botão de cadastrar um novo local na tela de confirmação de envio do formulário para voltar a tela do formulário

## Testes:
- [x] Correto redirecionamento do novo botão voltar a página inicial
- [x] Correto redirecionamento do botão cadastrar um novo local da página de confirmação de envio de formulário

**Comment by MarcosViniciusG** [comment]
Adicionei o botão voltar na tela final e modifiquei o botão de preencher novamente para redirecionar para o formulário. Também adicionei uma função de esvaziar os dados do formulário.
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/85762681/d855e583-f7f5-4cdb-aa0e-4b606084d720)
