### ISSUE TITLE
Estudo sobre capturar a localização do usuário da página

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#7]
# Etapas para validação:

- [x] estudo sobre como capturar a localização do usuário
- [x] estudo sobre o tratamento desses dados para iniciar o mapa
## Resumo sobre:

Estudo sobre como o plugin pode captar a localização do usário para iniciar o mapa

**Comment by Max-Rohrer20** [comment]
O estudo para o uso do plugin para utilizar a localização do usuário foi feita com sucesso, e já pode ser implementada dentro do código
