### ISSUE TITLE
Remoção do bug nas telas do plugin

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#74]
## Descrição:
Quando carregado o plugin em uma página o console do navegador aponta o seguinte erro: script.js:1 Uncaught SyntaxError: Unexpected token '<'

## Tarefas:
- [x] Atualizar o plugin para não retornar esse erro

## Testes:
- [x] Quando iniciado o plugin em uma página no wordpress não retornar o erro: script.js:1 Uncaught SyntaxError: Unexpected token '<'

**Comment by MarcosViniciusG** [comment]
Os bugs foram removidos em três situações: no site inteiro, na página onde está localizado o shortcode e na página do admin. Apenas possui um erro agora relacionado a exportação das classes e funções para testes, mas não interfere no funcionamento do código:
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/85762681/b19c0eec-738c-45c4-81e6-b0e554728145)
