### ISSUE TITLE
Adição de um sub menu dentro do menu do LGBTQ+ Connect

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#75]
## Descrição:
Dentro da interface do admin, se mostra necessário uma nova tela (sub menu) no qual o administrador terá acesso ao mapa com os locais já cadastrados plotados.

## Tarefas:
- [x] Criação de uma tela dentro do menu/interface do LGBTQ+ Connect dentro do wordpress
- [x] Nessa tela ter um mapa com os locais ja cadastrados

## Testes:
- [x] Correto funcionamento da interface do admin
- [x] Nova tela da interface contendo o mapa com os locais ja cadastrados

**Comment by MarcosViniciusG** [comment]
O mapa foi adicionado
![image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/85762681/19eae475-772f-4357-b0c9-56ba4e827a5c)
