### ISSUE TITLE
Resolvendo bug no envio de formulários sem marcador

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#78]
## Descrição:
No envio de formulário ainda se mostra possível enviá-lo sem marcador selecionado, o bug ocorre quando um marcador é adicionado e depois removido.

## Tarefas:
- [x] Formulários apenas serem enviados com um marcador ativo
- [x] Correto envio de informações do marcador para inputs de latitude e longitude

## Testes:
- [x] Formulários serem enviados se e somente se um marcador estiver selecionado no mapa

**Comment by Punkrig** [comment]
![Captura de tela de 2024-04-27 18-19-27](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/111445872/48695af5-90ba-47f9-8563-dee300e2cda7)
O bug foi corrigido, como podemos ver na imagem de tentartiva de envio de local sem a marcação no mapa
