### ISSUE TITLE
Adicionando novo texto no popup dos mapas

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#81]
## Descrição:
Quando o popup é mostrado com as interações no mapa, ele apenas mostra o nome do local quando clicado. É necessário adicionar um texto mais descritivo sobre o local clicado. Porém cada mapa deve mostrar um tipo de descrição, pois cada mapa possui um objetivo.

## Tarefas:
- [x] Atualizar o texto do popup para algo mais descritivo
- [x] As informações mostradas fazerem sentido para o mapa em questão
- [x] O visual do popup ser coerente com o mapa

## Testes:
- [x] Correto funcionamento do popup nos mapas
- [x] Informação ser relevante para cada mapa
- [x]  Correto funcionamento do popup com ações do usuário no mapa

**Comment by Max-Rohrer20** [comment]
Adicionei os pop-ups em todos os mapas relacionados ao plugin (mapa inicial, mapa do formulario, mapa de saida e mapa da página de administração)

Pop-up no mapa inicial:
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/d1cbe7ae-340d-4490-a2cb-7b6f1890d582)


Pop-up no mapa de formulário:
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/0a755ddf-c237-4c64-951f-a16bb8896bf9)

Pop-up no mapa de saída do formulário:
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/1f1036c7-fc79-4c05-916b-ba88a3c0d544)

Pop-up no mapa da página de administração:
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/bf24fe33-df8e-4499-8864-21cf6dca66a3)

OBS: Recomendo retirar o pop-up do mapa da página de administração, pois a presença dele é irrelevante se levarmos em conta a funcionalidade de destacar na tabela de formulários aprovados o cadastro correspondente.

**Comment by WillxBernardo** [comment]
Sim, é válida a remoção dos popups no mapa da interface do admin tendo em vista a funcionalidade de redirecionamento da página quando clicado em um marker.

**Comment by Max-Rohrer20** [comment]
Fiz a remoção do pop up do mapa da interface (página de administração)
