### ISSUE TITLE
Desenvolvimento de visual para os popups dos mapas

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#86]
## Descrição:
Os pop-ups apresentam um visual simples e apenas informativos, se mostra necessário o desenvolvimento de um visual mais trabalhado.

## Tarefas:
- [x] Desenvolver um pop-up trabalhado para a experiência dos usuário
- [x] O popup deve conter as informações relevantes para o contexto do mapa

## Testes:
- [x] Pop-ups com um visual condizente com o uso do plugin
- [x] Pop-ups contendo informações relevantes para o usuário

**Comment by Max-Rohrer20** [comment]
O novo visual dos Pop-Ups foi feito baseado no wireframe feito pelo @guslnhm. Abaixo segue um print de como está a apresentação deles na primeira versão desse novo visual.

![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/cfa0bd40-1d08-409b-91fe-f41da4bd5396)

![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/659c42b3-5c92-4b0e-a387-4cde14c5d7fc)

![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/160171332/f2664bbd-1f97-47b3-9898-00017bc2b6dc)
