### ISSUE TITLE
Análise sobre os códigos de mapa

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#87]
## Descrição:
Atualmente os códigos para gerar mapas são feitos para cada mapa individualmente, houve uma tentativa de padronização para uso das mesmas funções porém não foi possível em um primeiro momento. Visando gerar código da forma mais limpa possível necessita uma análise sobre os códigos para uma tentativa de melhor abordagem e futuras implementações.

## Tarefas:
- [x] Analisar os código javascript para plotagem dos mapas
- [x] Retornar análise para equipa para decisão sobre possível reestruturação do código

**Comment by MarcosViniciusG** [comment]
O estudo foi realizado e a equipe aprovou a proposta de reestruturação do código da frontend para seguir o paradigma de orientação a objetos.
