### ISSUE TITLE
Estilização dos campos de busca

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#90]
## Descrição:
Os campos de busca e os resultados mostrados se mostra necessário a estilização para ser relacionado com a identidade visual do projeto. Os resultados necessitam a atenção pois é um bloco refém do conteúdo resultante da API.

## Tarefas:
- [x] Estilização do campo de busca nas telas inicial e do formulário

## Testes:
- [x] Campos de busca e resultados conformes com o design das telas

**Comment by guslnhm** [comment]
O campo de pesquisa agora está consoante com a identidade visual do plugin. Foi adicionado, ainda, um placeholder que indica que a pesquisa retorna apenas cidades ou estados, e não os serviços e empreendimentos já avaliados.

Tela inicial:
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/143884487/df42636a-5994-426a-b96e-83d2553b4833)


Tela do formulário:
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/143884487/465028a2-d4a1-45b1-a60a-17c6e2ceb60d)
