### ISSUE TITLE
Adição de uma notificação após ações do administrador

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#96]
## Descrição:
Após alguma ação (excluir, aprovar e negar) do admin é necessário notificá-lo  (no mesmo ambiente/tela) para confirmação visual para o admin.

## Tarefas:
- [ ] Escolha das formas de notificação (popups, tags html, ...)
- [ ] Revisão com o time sobre a escolha
- [ ] Implementação da notificação na interface do administrador

## Testes:
- [ ] Notificação na interface do admin após alguma ação
- [ ] Notificação estar de acordo com a identidade visual da interface
- [ ] Correto funcionamento dentro da interface (Não atrapalhar outras funcionalidades)

**Comment by Punkrig** [comment]
![Captura de tela de 2024-05-17 09-46-34](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/111445872/fc81eafe-a2f0-4f34-8a93-3799187b1dab)
![Uploading Captura de tel
![Captura de tela de 2024-05-17 09-47-02](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/111445872/0d63869c-4279-46d4-87b2-ae84bb74bdcd)
a de 2024-05-17 09-46-51.png…]()
Notificações para o usuário
