### ISSUE TITLE
Trabalho visual nos resultados da busca

### ISSUE THREAD

**Issue by WillxBernardo** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#97]
## Descrição:
Os resultados mostrados após a busca não estão de acordo com o visual do plugin, visando melhor experiência de usuário mostra-se necessário definir uma forma limpa de resultados.

## Tarefas:
- [x] Resultados das buscas nas telas estarem de acordo com o design da tela

## Testes:
- [x] Campos de resultado de acordo com o visual da tela
- [x] Correto funcionamento das funcionalidades presentes nas telas

**Comment by guslnhm** [comment]
![Image](https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress/assets/143884487/e64deadf-b79f-4d00-a3ab-0bfb3a3d0320)
